### ISSUE TITLE
global: use fixtures to populate the database

### ISSUE THREAD

**Issue by jbenito3** [inveniosoftware/claimstore#20]
At the time being a quick solution was done at app-creation time. Fixtures would be a better approach.

**Comment by tiborsimko** [comment]
See also [mixer](http://mixer.readthedocs.org/en/latest/) that CDS is using in the LABS overlay.

**Comment by tiborsimko** [comment]
Moreover, the CLI command semantics may be changed:

- `initdb` should create tables and initialise the good "reference" values such as known claimants, known predicates, etc.  (coming from fixtures)

- `populatedb` should basically create a demo site with a set of several claims (=coming from JSON files) that can be used for testing intelligent claim retrieval, e.g. #49.

In this way, when people launch `docker-compose up`, they will basically obtain a pre-populated "demo site" that will more readily permit to demo its functioning.

For developers, note that the usual `python setup.py test` should take care of nicely cleaning after itself, so that the final state would be always the same as after running initdb and populatedb.

**Comment by tiborsimko** [comment]
Summary of live discussion with @jbenito3 :

The first step, defining our collaborative network, means to define managed persisent ids, claimans, predicates, etc.  This can have a structure like:

```
tests/myclaimstore/config/pids/inspire-id.json
tests/myclaimstore/config/pids/inspire-author-id.json
tests/myclaimstore/config/pids/arxiv-id.json
tests/myclaimstore/config/pids/ads-bibcode.json
tests/myclaimstore/config/pids/doi.json
tests/myclaimstore/config/pids/orcid.json
tests/myclaimstore/config/claimants/inspire.json
tests/myclaimstore/config/claimants/arxiv.json
tests/myclaimstore/config/claimants/ads.json
tests/myclaimstore/config/predicates/is_same_as.json
tests/myclaimstore/config/predicates/is_variant_of.json
tests/myclaimstore/config/predicates/is_author_of.json
tests/myclaimstore/config/predicates/is_contributor_to.json
tests/myclaimstore/config/predicates/is_erratum_of.json
[...]
```

for each "configuration" DB table.  (In the above example, the table rows are split into individual files, while it may be sufficient to have one file per table.)

Then a command like `claimstore init --config ./tests/myclaimstore/config` would read this "configuration data" and would create and initialise DB tables accordingly, for example using [mixer](http://mixer.readthedocs.org/en/latest/).  After this step, our system is defined and ready to accept "runtime data", i.e. claims.

The second step, then, would populate the system with runtime claim data, which can be used e.g. for testing intelligent claim retrieval #49.  This can have a strucure like:

```
tests/myclaimstore/data/claims/test_claim_incorrect.json
tests/myclaimstore/data/claims/test_claim_correct.json
tests/myclaimstore/data/claims/small_test_set.json
tests/myclaimstore/data/claims/big_demo_set.json
[...]
```

`claimstore upload <filename>` could populate previously defined network with given wanted test claim data.

Thirdly, the usual test suite for subscribing new partners to the network (etc) can use any random Foo data defined as fixtures *inside* the test suite files, paying attention in the tear down procedures to remove only those submitted test entries, not the whole network.
